In [5]:
import numpy as np

In [29]:
arr_01 = np.array([[0,1,2,3,257],[3,4,6,6,258]], dtype=np.int8)
arr_01

C:\Users\jhona\AppData\Local\Temp\ipykernel_23944\416811886.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 257 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr_01 = np.array([[0,1,2,3,257],[3,4,6,6,258]], dtype=np.int8)
C:\Users\jhona\AppData\Local\Temp\ipykernel_23944\416811886.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 258 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr_01 = np.array([[0,1,2,3,257],[3,4,6,6,258]], dtype=np.int8)


array([[0, 1, 2, 3, 1],
       [3, 4, 6, 6, 2]], dtype=int8)

In [10]:
arr_01 = np.array([[0,1,2,3,257],[3,4,6,6,258]], dtype=np.int32)
arr_01

array([[  0,   1,   2,   3, 257],
       [  3,   4,   6,   6, 258]])

In [11]:
arr_02 = np.arange(start=0,stop=10,step=3)
arr_02

array([0, 3, 6, 9])

In [27]:
arr_03 = np.ones((2,2))
arr_03

array([[1., 1.],
       [1., 1.]])

In [31]:
arr_04 = np.linspace(start=10,stop=100,num=10,endpoint=True,retstep=True)
arr_04

(array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]), 10.0)