In [5]:
import numpy as np

In [28]:
arr_01 = np.array([[0,1,2,3,257],[3,4,6,6,258]], dtype=np.int32)
arr_01

array([[  0,   1,   2,   3, 257],
       [  3,   4,   6,   6, 258]])

In [10]:
arr_01 = np.array([[0,1,2,3,257],[3,4,6,6,258]], dtype=np.int32)
arr_01

array([[  0,   1,   2,   3, 257],
       [  3,   4,   6,   6, 258]])

In [11]:
arr_02 = np.arange(start=0,stop=10,step=3)
arr_02

array([0, 3, 6, 9])

In [27]:
arr_03 = np.ones((2,2))
arr_03

array([[1., 1.],
       [1., 1.]])

In [26]:
arr_04 = np.linspace(start=10,stop=100,num=12,endpoint=False,retstep=True)
arr_04

(array([10. , 17.5, 25. , 32.5, 40. , 47.5, 55. , 62.5, 70. , 77.5, 85. ,
        92.5]),
 7.5)